const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:890,height:400},timezoneId:'America/Los_Angeles'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:new Date('2026-09-30T11:59:55Z')});
 await page.addInitScript(()=>{window.quietCalls=[];window.sent=[];window.DashboardNative={refresh(){},isConfigured(){return false;},setQuietMode(q){quietCalls.push(q);},sendAction(op){sent.push(JSON.parse(op));}};});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../web/index.html')).href);
 assert.ok(await page.locator('#page-today').isVisible());
 assert.match(await page.locator('#today-status').textContent(),/DEMO/);
 await page.clock.runFor(6000);assert.equal(await page.evaluate(()=>quietCalls.at(-1)),true);
 await page.locator('#today-shopping').click();assert.equal(await page.evaluate(()=>quietCalls.at(-1)),false,'touch brightens');
 await page.clock.fastForward(121000);assert.equal(await page.evaluate(()=>quietCalls.at(-1)),true);
 await page.locator('#add-shopping').click();await page.locator('#task-title').fill('Milk');await page.locator('#task-quantity').fill('2');await page.locator('#task-category').selectOption('Dairy');await page.locator('.task-save').click();
 await page.getByRole('button',{name:'Increase quantity of Milk',exact:true}).click();assert.equal(await page.evaluate(()=>taskItems()[0].quantity),3);
 await page.getByRole('button',{name:'Check off Milk',exact:true}).click();assert.equal(await page.locator('.completed-shopping').getAttribute('open'),null);
 await page.locator('.completed-shopping summary').click();await page.getByRole('button',{name:'Undo',exact:true}).click();
 await page.locator('#add-reminder').click();await page.locator('#task-title').fill('Bins out');await page.locator('#task-due').fill('2026-10-01T20:00');await page.locator('#task-repeat').selectOption('weekly');await page.locator('.task-save').click();
 await page.getByRole('button',{name:'Mark Bins out done',exact:true}).click();assert.equal(await page.evaluate(()=>taskItems().find(i=>i.kind==='reminder').due_at),'2026-10-08T09:00:00.000Z');
 await page.locator('#reminder-list-close').click();await page.locator('[data-page=today]').click();await page.clock.runFor(1100);
 assert.match(await page.locator('#today-shopping-preview').textContent(),/Milk ×3/);assert.match(await page.locator('#today-reminder-time').textContent(),/weekly/);
 await page.clock.setSystemTime(new Date('2026-09-30T21:00:00Z'));await page.clock.runFor(1000);assert.equal(await page.evaluate(()=>quietCalls.at(-1)),false,'7am restores brightness');
 await page.reload();assert.equal(await page.evaluate(()=>taskItems().find(i=>i.kind==='shopping').quantity),3);
 await page.screenshot({path:path.resolve(__dirname,'../build/today-preview.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await page.evaluate(()=>taskState.routineBlocked),true,'enhanced operations wait for compatible Mac');
 await page.evaluate(()=>acceptTasks({instance:'upgraded-mac',capabilities:['routines-v1'],items:[]}));
 assert.equal(await page.evaluate(()=>taskState.routineBlocked),false);assert.equal(await page.evaluate(()=>sent[0].quantity),2,'resume original operation when updated Mac arrives');
 assert.deepEqual(errors,[]);console.log('PASS: Today, Sydney quiet boundaries/tap brightness, quantities/category/completed collapse, offline recurring reminders and restart.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
